import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Shirt, ReceiptText, Plus, Search, ArrowUpRight, ArrowDownToLine, Upload, X, Check, Package, ShoppingBag, Wallet, TrendingUp, ChevronRight, Menu, CircleHelp, RotateCcw } from 'lucide-react';
import { KEY, types, emptyStore, localDate, cents, newId, validateStore, recordSale, totals, balance } from './store';
import Expenses from './Expenses';
import './styles.css';
import './brand-theme.css';

function App() {
  const [initial] = useState(() => { try { const raw = localStorage.getItem(KEY); return { data: raw ? validateStore(JSON.parse(raw)) : emptyStore(), error: '' }; } catch { return { data: emptyStore(), error: 'No pudimos leer tus datos guardados. Exporta una copia de recuperación antes de iniciar un inventario nuevo.', blocked: true }; } });
  const [data, setData] = useState(initial.data);
  const [error, setError] = useState(initial.error);
  const [blocked, setBlocked] = useState(initial.blocked);
  const [page, setPage] = useState('Resumen');
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Todas');
  const [stock, setStock] = useState('Todos');
  const [modal, setModal] = useState(null);
  const [notice, setNotice] = useState('');
  const [today, setToday] = useState(localDate());
  const [month, setMonth] = useState(localDate().slice(0, 7));
  const [day, setDay] = useState(localDate());
  const [mobile, setMobile] = useState(false);
  const upload = useRef(null);
  useEffect(() => { const timer = setInterval(() => setToday(localDate()), 30000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (notice) { const timer = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timer); } }, [notice]);
  const money = n => new Intl.NumberFormat('es', { style: 'currency', currency: data.currency, currencyDisplay: 'code' }).format(n / 100);
  function save(next, message, recovery = false) {
    if (blocked && !recovery) { setError('Primero recupera tus datos desde un respaldo.'); return false; }
    try { const validated = validateStore(next); localStorage.setItem(KEY, JSON.stringify(validated)); setData(validated); setBlocked(false); setError(''); if (message) setNotice(message); return true; }
    catch (e) { setError(`No se pudo guardar: ${e.message}. Revisa el espacio disponible del navegador.`); return false; }
  }
  function download(raw, filename) {
    const url = URL.createObjectURL(new Blob([raw], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  async function importFile(e) {
    const file = e.target.files[0]; e.target.value = ''; if (!file) return;
    try { if (file.size > 10000000) throw new Error('El archivo supera los 10 MB.'); const backup = validateStore(JSON.parse(await file.text())); setModal({ kind: 'import', backup }); } catch (e) { setError(e.message); }
  }
  const todaySales = data.sales.filter(s => s.date === today);
  const monthSales = data.sales.filter(s => s.date.startsWith(month));
  const daily = totals(todaySales), monthly = balance(data, month), dayBalance = balance(data, day);
  const units = data.products.reduce((a, p) => a + p.quantity, 0);
  const inventoryCost = data.products.reduce((a, p) => a + p.quantity * p.buy, 0);
  const filtered = data.products.filter(p => `${p.name} ${p.type}`.toLowerCase().includes(query.toLowerCase()) && (category === 'Todas' || p.type === category) && (stock === 'Todos' || (stock === 'Disponibles' ? p.quantity > 0 : p.quantity === 0)));
  const recent = [...data.sales].reverse().slice(0, 5);
  const monthName = new Date(`${month}-02T12:00:00`).toLocaleDateString('es', { month: 'long', year: 'numeric' });
  function openSale(p) { setModal({ kind: 'sale', product: p }); }
  function submitProduct(e) {
    e.preventDefault(); const f = new FormData(e.target); const name = f.get('name').trim(); if (!name) return;
    const product = { id: newId(), name, type: f.get('type'), quantity: Number(f.get('quantity')), buy: cents(f.get('buy')), sell: cents(f.get('sell')), created: today };
    if (save({ ...data, products: [...data.products, product] }, 'Prenda agregada al inventario')) setModal(null);
  }
  function submitSale(e) { e.preventDefault(); try { const quantity = modal.product.quantity === 1 ? 1 : Number(new FormData(e.target).get('quantity')); if (save(recordSale(data, modal.product.id, quantity), 'Venta registrada correctamente')) setModal(null); } catch (e) { setError(e.message); } }
  function navigate(p) { setPage(p); setMobile(false); }
  const week = Array.from({ length: 7 }, (_, i) => { const date = new Date(`${today}T12:00:00`); date.setDate(date.getDate() - 6 + i); const key = localDate(date); return { key, label: date.toLocaleDateString('es', { weekday: 'short' }).replace('.', ''), ...totals(data.sales.filter(s => s.date === key)) }; });
  const maxWeek = Math.max(...week.map(d => d.revenue), 1);
  const categories = types.map(type => ({ type, ...totals(monthSales.filter(s => s.type === type)) })).filter(c => c.units).sort((a, b) => b.units - a.units);
  return <div className="app">
    <aside className={`sidebar ${mobile ? 'open' : ''}`}>
      <a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('Resumen'); }}><span className="brand-icon"><ShoppingBag size={24}/></span><span>EMI<span className="brand-light"> Shop</span><small>INVENTARIO & VENTAS</small></span></a>
      <div className="nav-caption">TU ESPACIO DE TRABAJO</div>
      <nav>{[['Resumen', LayoutDashboard], ['Inventario', Shirt], ['Registro de ventas', ReceiptText], ['Gastos', Wallet]].map(([label, Icon]) => <button key={label} className={page === label ? 'nav active' : 'nav'} onClick={() => navigate(label)}><Icon size={19}/>{label}{page === label && <span className="active-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="local-card"><span className="local-dot"/> Guardado local<small>Tus datos se guardan en este navegador. Crea respaldos con frecuencia.</small><button onClick={() => download(blocked ? localStorage.getItem(KEY) || '{}' : JSON.stringify(data, null, 2), `emi-shop-${today}.json`)}><ArrowDownToLine size={15}/> Exportar respaldo</button><button onClick={() => upload.current.click()}><Upload size={15}/> Importar respaldo</button></div><div className="profile"><span>ES</span><div>EMI Shop<small>Mi tienda de ropa</small></div><span className="profile-dot"/></div></div>
    </aside>
    <main><header className="topbar"><div><button className="mobile-menu icon-button" aria-label="Abrir menú" onClick={() => setMobile(!mobile)}><Menu/></button><span className="breadcrumb">Mi tienda <ChevronRight size={14}/> <strong>{page}</strong></span></div><span className="date-top">{new Date(`${today}T12:00:00`).toLocaleDateString('es', { day: 'numeric', month: 'long', year: 'numeric' })}</span></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">CADA PRENDA CUENTA</div><h1>{page === 'Resumen' ? 'Tu tienda, de un vistazo' : page === 'Inventario' ? 'Tu inventario' : page === 'Gastos' ? 'Gastos de la tienda' : 'Registro de ventas'}</h1><p>{page === 'Resumen' ? 'Todo lo que necesitas para seguir creciendo.' : page === 'Inventario' ? 'Organiza tus prendas y mantén tu stock al día.' : page === 'Gastos' ? 'Tus pagos, tus deducciones y lo que realmente queda.' : 'Cada venta guardada, cada día bajo control.'}</p></div>{page !== 'Gastos' && <button className="primary" onClick={() => setModal({ kind: 'product' })}><Plus size={18}/> Nueva prenda</button>}</div>
      {error && <div className="error" role="alert">{error}<button aria-label="Cerrar aviso" onClick={() => setError('')}><X size={16}/></button></div>}
      {page === 'Gastos' && <Expenses data={data} save={save} money={money} today={today} Modal={Modal} ModalActions={ModalActions}/>}
      {page === 'Resumen' && <>
        <div className="stats"><Stat title="Ventas de hoy" value={money(daily.revenue)} detail={`${daily.units} prendas vendidas hoy`} icon={Wallet} primary/><Stat title="Ventas del mes" value={money(monthly.revenue)} detail={monthName} icon={TrendingUp}/><Stat title="Ganancia neta del mes" value={money(monthly.net)} detail="Descontando costo de prendas y gastos" icon={ArrowUpRight}/><Stat title="Prendas disponibles" value={units} detail={`${data.products.filter(p => p.quantity > 0).length} referencias en inventario`} icon={Shirt}/></div>
        <div className="dashboard-grid"><section className="panel sales-chart"><div className="panel-head"><div><h2>Así van tus ventas</h2><p>Ingresos de los últimos 7 días</p></div><span className="chip"><span/> Ventas</span></div><div className="chart-total">{money(week.reduce((a, d) => a + d.revenue, 0))}<span>esta semana</span></div><div className="chart"><div className="chart-grid"/><div className="bars">{week.map(d => <div className="bar-column" key={d.key}><div className={`bar ${d.key === today ? 'current' : ''}`} style={{ height: `${d.revenue ? Math.max(4, d.revenue / maxWeek * 100) : 2}%` }} title={`${d.key}: ${money(d.revenue)}`}><span>{money(d.revenue)}</span></div><label>{d.key === today ? 'Hoy' : d.label}</label></div>)}</div></div></section>
        <section className="panel month-panel"><div className="panel-head"><div><h2>Balance mensual</h2><p>El resultado de tu trabajo</p></div><TrendingUp size={19}/></div><label className="sr-only" htmlFor="month">Mes del balance</label><input id="month" className="month-input" type="month" value={month} onChange={e => e.target.value && setMonth(e.target.value)}/><div className="balance-line"><span>Total vendido</span><strong>{money(monthly.revenue)}</strong></div><div className="balance-line"><span>Costo de prendas vendidas</span><strong>{money(monthly.cost)}</strong></div><div className="balance-line"><span>Gastos de la tienda</span><strong>{money(monthly.expenses)}</strong></div><div className="profit"><span>Ganancia después de gastos<strong>{money(monthly.net)}</strong></span><ArrowUpRight size={25}/></div><p className="fine-print">Incluye los gastos registrados en el mes seleccionado.</p><div className="month-units"><ShoppingBag size={16}/><strong>{monthly.units}</strong> prendas vendidas este mes</div></section></div>
        <div className="dashboard-grid bottom-grid"><section className="panel"><div className="panel-head"><div><h2>Últimas ventas</h2><p>Los movimientos más recientes de tu tienda</p></div><button className="text-button" onClick={() => navigate('Registro de ventas')}>Ver todas <ChevronRight size={15}/></button></div>{recent.length ? <SalesTable sales={recent} money={money}/> : <Empty icon={ReceiptText} title="Tu próxima venta empieza aquí" text="Cuando vendas una prenda, aparecerá en este registro." action="Ir al inventario" onClick={() => navigate('Inventario')}/>}</section><section className="panel"><div className="panel-head"><div><h2>Lo más vendido</h2><p>Por tipo de prenda · {monthName}</p></div><Shirt size={19}/></div>{categories.length ? <div className="category-list">{categories.slice(0, 5).map((c, i) => <div className="category-row" key={c.type}><span className="rank">0{i + 1}</span><div><strong>{c.type}</strong><div className="progress"><span style={{ width: `${c.units / monthly.units * 100}%` }}/></div></div><span>{c.units} uds.</span></div>)}</div> : <Empty icon={Shirt} title="Cada estilo tiene su momento" text="Descubre tus categorías favoritas al registrar ventas."/>}</section></div>
        <div className="inventory-note"><Package size={19}/><span>Tienes <strong>{money(inventoryCost)}</strong> invertidos en las prendas disponibles.</span><button className="text-button" onClick={() => navigate('Inventario')}>Ver inventario <ArrowUpRight size={16}/></button></div>
      </>}
      {page === 'Inventario' && <><div className="inventory-summary"><span><strong>{units}</strong> unidades disponibles</span><span><strong>{data.products.length}</strong> referencias</span><span><strong>{money(inventoryCost)}</strong> costo del inventario</span></div><section className="panel"><div className="filters"><label className="search"><Search size={18}/><input placeholder="Buscar por nombre o marca…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Tipo de prenda" value={category} onChange={e => setCategory(e.target.value)}><option>Todas</option>{types.map(t => <option key={t}>{t}</option>)}</select><select aria-label="Disponibilidad" value={stock} onChange={e => setStock(e.target.value)}>{['Todos', 'Disponibles', 'Agotados'].map(t => <option key={t}>{t}</option>)}</select></div>{filtered.length ? <div className="table-wrap inventory-table"><table><thead><tr><th>Prenda / marca</th><th>Tipo</th><th>Stock</th><th>Compra</th><th>Venta</th><th>Acciones</th></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td><div className="product-name"><span className="product-icon"><Shirt size={19}/></span><strong>{p.name}</strong></div></td><td>{p.type}</td><td><span className={`badge ${p.quantity === 0 ? 'out' : p.quantity <= 3 ? 'low' : ''}`}>{p.quantity === 0 ? 'Agotado' : `${p.quantity} uds.`}</span></td><td>{money(p.buy)}</td><td className="amount">{money(p.sell)}</td><td><div className="row-actions"><button className="sell-button" disabled={!p.quantity} onClick={() => openSale(p)}><Check size={14}/> Vendida</button><button className="icon-button" title="Agregar existencias" aria-label={`Agregar existencias de ${p.name}`} onClick={() => setModal({ kind: 'restock', product: p })}><Plus size={17}/></button></div></td></tr>)}</tbody></table></div> : <Empty icon={Shirt} title={data.products.length ? 'No encontramos prendas' : 'Dale la bienvenida a tu primera prenda'} text={data.products.length ? 'Prueba con otro nombre o cambia los filtros.' : 'Agrega tu mercancía para empezar a organizar EMI Shop.'} action={data.products.length ? undefined : 'Agregar prenda'} onClick={() => setModal({ kind: 'product' })}/>}</section></>}
      {page === 'Registro de ventas' && <><div className="sales-filters"><label>Día del registro<input type="date" value={day} onChange={e => e.target.value && setDay(e.target.value)}/></label><button className="secondary" onClick={() => setDay(today)}>Hoy</button></div><div className="stats three"><Stat title="Ventas del día" value={money(totals(data.sales.filter(s => s.date === day)).revenue)} detail={day} icon={Wallet} primary/><Stat title="Ganancia neta del día" value={money(dayBalance.net)} detail="Después de costo de prendas y gastos" icon={TrendingUp}/><Stat title="Prendas vendidas" value={totals(data.sales.filter(s => s.date === day)).units} detail="Unidades vendidas en este día" icon={ShoppingBag}/></div><section className="panel daily-deductions"><div className="balance-line"><span>Costo de prendas vendidas</span><strong>{money(dayBalance.cost)}</strong></div><div className="balance-line"><span>Gastos del día</span><strong>{money(dayBalance.expenses)}</strong></div><div className="balance-line"><span>Ganancia después de gastos</span><strong>{money(dayBalance.net)}</strong></div></section><section className="panel"><div className="panel-head"><div><h2>Detalle del día</h2><p>Las ventas se conservan aunque cambie el inventario.</p></div></div>{data.sales.some(s => s.date === day) ? <SalesTable sales={data.sales.filter(s => s.date === day).reverse()} money={money} onUndo={s => setModal({ kind: 'undo', sale: s })}/> : <Empty icon={ReceiptText} title="Sin ventas en esta fecha" text="Selecciona otro día o registra una venta desde el inventario."/>}</section></>}
      <footer><span>EMI Shop <span className="footer-dot">·</span> Un poco más organizada, un paso más lejos.</span><label>Moneda <select aria-label="Moneda de la tienda" value={data.currency} onChange={e => setModal({ kind: 'currency', currency: e.target.value })}>{['USD', 'VES', 'EUR', 'COP', 'MXN'].map(c => <option key={c}>{c}</option>)}</select></label></footer></div>
    </main><input ref={upload} type="file" accept="application/json,.json" hidden onChange={importFile}/>
    {notice && <div className="toast" role="status"><Check size={18}/>{notice}</div>}
    {modal && <Modal title={{ product: 'Nueva prenda', sale: 'Registrar venta', restock: 'Agregar existencias', import: 'Restaurar respaldo', undo: 'Anular venta', currency: 'Cambiar moneda' }[modal.kind]} onClose={() => setModal(null)}>
      {modal.kind === 'product' && <form onSubmit={submitProduct}><p className="modal-intro">Cuéntanos qué llegó a tu tienda.</p><label>Marca o nombre<input name="name" autoFocus required maxLength={100} placeholder="Ej. Blusa de lino Zara"/></label><label>Tipo de prenda<select name="type">{types.map(t => <option key={t}>{t}</option>)}</select></label><label>Cantidad<input name="quantity" type="number" required min="1" max="1000000" step="1" defaultValue="1"/></label><div className="form-grid"><label>Precio de compra ({data.currency})<input name="buy" type="number" required min="0" max="100000000" step="0.01" placeholder="0.00"/></label><label>Precio de venta ({data.currency})<input name="sell" type="number" required min="0" max="100000000" step="0.01" placeholder="0.00"/></label></div><p className="help-text"><CircleHelp size={14}/> Ingresa los precios por unidad.</p><ModalActions close={() => setModal(null)} label="Agregar al inventario"/></form>}
      {modal.kind === 'sale' && <form onSubmit={submitSale}><div className="selected-product"><Shirt/><div><strong>{modal.product.name}</strong><small>{modal.product.quantity} disponibles · {money(modal.product.sell)} por unidad</small></div></div>{modal.product.quantity > 1 ? <label>¿Cuántas unidades vendiste?<input autoFocus name="quantity" type="number" min="1" max={modal.product.quantity} step="1" defaultValue="1" required/></label> : <p>Se registrará la venta de 1 unidad por {money(modal.product.sell)}.</p>}<p className="help-text">La venta se registrará hoy y se descontará del inventario.</p><ModalActions close={() => setModal(null)} label="Confirmar venta"/></form>}
      {modal.kind === 'restock' && <form onSubmit={e => { e.preventDefault(); const n = Number(new FormData(e.target).get('quantity')); if (save({ ...data, products: data.products.map(p => p.id === modal.product.id ? { ...p, quantity: p.quantity + n } : p) }, 'Existencias actualizadas')) setModal(null); }}><p className="modal-intro">Agregar unidades de <strong>{modal.product.name}</strong>.</p><label>Unidades recibidas<input name="quantity" type="number" autoFocus min="1" max={1000000 - modal.product.quantity} step="1" required defaultValue="1"/></label><p className="help-text">Se conservan los precios actuales. Si cambió el costo de compra, registra la mercancía como una nueva prenda.</p><ModalActions close={() => setModal(null)} label="Agregar existencias"/></form>}
      {modal.kind === 'import' && <><p>Este respaldo tiene <strong>{modal.backup.products.length} prendas</strong> y <strong>{modal.backup.sales.length} ventas</strong> y <strong>{modal.backup.expenses.length} gastos</strong>. Reemplazará los datos actuales.</p><p className="help-text">Exporta primero tus datos actuales si deseas conservarlos.</p><ModalActions close={() => setModal(null)} label="Restaurar datos" onConfirm={() => { if (save(modal.backup, 'Respaldo restaurado', true)) setModal(null); }}/></>}
      {modal.kind === 'undo' && <><p>Se anulará la venta de <strong>{modal.sale.quantity} × {modal.sale.name}</strong>. Las unidades volverán al inventario y los totales se actualizarán.</p><ModalActions close={() => setModal(null)} label="Anular venta" onConfirm={() => { const s = modal.sale; if (save({ ...data, sales: data.sales.filter(x => x.id !== s.id), products: data.products.map(p => p.id === s.productId ? { ...p, quantity: p.quantity + s.quantity } : p) }, 'Venta anulada y stock recuperado')) setModal(null); }}/></>}
      {modal.kind === 'currency' && <><p>Los importes se mostrarán en <strong>{modal.currency}</strong>. Esta opción cambia la moneda de toda la tienda; no convierte los valores guardados.</p><ModalActions close={() => setModal(null)} label="Cambiar moneda" onConfirm={() => { if (save({ ...data, currency: modal.currency }, 'Moneda actualizada')) setModal(null); }}/></>}
    </Modal>}
  </div>;
}
function Stat({ title, value, detail, icon: Icon, primary }) { return <section className={`stat ${primary ? 'stat-primary' : ''}`}><div className="stat-title">{title}<span><Icon size={19}/></span></div><strong className="stat-value">{value}</strong><small>{detail}</small></section>; }
function Empty({ icon: Icon, title, text, action, onClick }) { return <div className="empty"><span className="empty-icon"><Icon size={25}/></span><h3>{title}</h3><p>{text}</p>{action && <button className="text-button" onClick={onClick}>{action}<ArrowUpRight size={15}/></button>}</div>; }
function SalesTable({ sales, money, onUndo }) { return <div className="table-wrap"><table><thead><tr><th>Prenda</th><th>Fecha</th><th>Cantidad</th><th>Total</th>{onUndo && <th/>}</tr></thead><tbody>{sales.map(s => <tr key={s.id}><td><div className="product-name"><span className="product-icon"><Shirt size={17}/></span><div><strong>{s.name}</strong><small>{s.type}</small></div></div></td><td>{s.date.split('-').reverse().join('/')}<small>{new Date(s.time).toLocaleTimeString('es', { hour: '2-digit', minute: '2-digit' })}</small></td><td>{s.quantity}</td><td className="amount">{money(s.sell * s.quantity)}</td>{onUndo && <td><button className="icon-button" aria-label={`Anular venta de ${s.name}`} title="Anular venta" onClick={() => onUndo(s)}><RotateCcw size={16}/></button></td>}</tr>)}</tbody></table></div>; }
function ModalActions({ close, label, onConfirm }) { return <div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" type={onConfirm ? 'button' : 'submit'} onClick={onConfirm}>{label}</button></div>; }
function Modal({ title, children, onClose }) {
  const ref = useRef(null);
  useEffect(() => { const previous = document.activeElement; ref.current.showModal(); return () => { previous?.focus(); }; }, []);
  return <dialog ref={ref} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === ref.current) onClose(); }}><div className="modal-inner"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Cerrar" onClick={onClose}><X size={20}/></button></div>{children}</div></dialog>;
}
createRoot(document.getElementById('root')).render(<App/>);


